export enum NotificationEvent {
  // Cliente
  CUSTOMER_WELCOME = "CUSTOMER_WELCOME",
  CUSTOMER_VERIFY_EMAIL = "CUSTOMER_VERIFY_EMAIL",
  CUSTOMER_PASSWORD_RESET = "CUSTOMER_PASSWORD_RESET",
  CUSTOMER_PASSWORD_CHANGED = "CUSTOMER_PASSWORD_CHANGED",
  CUSTOMER_ACCOUNT_DISABLED = "CUSTOMER_ACCOUNT_DISABLED",
  ORDER_CREATED = "ORDER_CREATED",
  ORDER_ACCEPTED = "ORDER_ACCEPTED",
  ORDER_PREPARING = "ORDER_PREPARING",
  DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
  ORDER_ON_THE_WAY = "ORDER_ON_THE_WAY",
  ORDER_DELIVERED = "ORDER_DELIVERED",
  ORDER_CANCELLED = "ORDER_CANCELLED",

  // Repartidor
  DRIVER_WELCOME = "DRIVER_WELCOME",
  DRIVER_VERIFY_EMAIL = "DRIVER_VERIFY_EMAIL",
  DRIVER_DOCS_RECEIVED = "DRIVER_DOCS_RECEIVED",
  DRIVER_APPROVED = "DRIVER_APPROVED",
  DRIVER_REJECTED = "DRIVER_REJECTED",
  DRIVER_SUSPENDED = "DRIVER_SUSPENDED",
  DRIVER_PASSWORD_RESET = "DRIVER_PASSWORD_RESET",
  DRIVER_NEW_ORDER = "DRIVER_NEW_ORDER",
  DRIVER_ORDER_PICKED_UP = "DRIVER_ORDER_PICKED_UP",
  DRIVER_ORDER_DELIVERED = "DRIVER_ORDER_DELIVERED",
  DRIVER_ORDER_CANCELLED = "DRIVER_ORDER_CANCELLED",

  // Restaurante
  RESTAURANT_APPLICATION_RECEIVED = "RESTAURANT_APPLICATION_RECEIVED",
  RESTAURANT_UNDER_REVIEW = "RESTAURANT_UNDER_REVIEW",
  RESTAURANT_APPROVED = "RESTAURANT_APPROVED",
  RESTAURANT_REJECTED = "RESTAURANT_REJECTED",
  RESTAURANT_DOCS_REQUIRED = "RESTAURANT_DOCS_REQUIRED",
  RESTAURANT_SUSPENDED = "RESTAURANT_SUSPENDED",
  RESTAURANT_REACTIVATED = "RESTAURANT_REACTIVATED",
  RESTAURANT_PASSWORD_RESET = "RESTAURANT_PASSWORD_RESET",
  RESTAURANT_NEW_ORDER = "RESTAURANT_NEW_ORDER",
  RESTAURANT_ORDER_ACCEPTED = "RESTAURANT_ORDER_ACCEPTED",
  RESTAURANT_ORDER_CANCELLED = "RESTAURANT_ORDER_CANCELLED",
}

export interface EmailRecipient {
  email: string;
  name: string;
  userId?: number;
}

export interface EmailPayload {
  recipient: EmailRecipient;
  event: NotificationEvent;
  eventId: string; // Unique deduplication key: e.g. "order_102_accepted", "restaurant_5_approved"
  data: Record<string, any>;
}
